import { mount } from '@vue/test-utils'
import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest'
import AppUpdates from './AppUpdates.vue'
import updates from '@/service/updates'

vi.mock('@/service/updates', () => ({ default: { list: vi.fn(), check: vi.fn(), update: vi.fn(), rollback: vi.fn() } }))
vi.mock('@/mixins/base/common-i18n', () => ({ ice_i18n: title => title.en_us }))
const app = overrides => ({ id: 'audiobookshelf', title: { en_us: 'Audiobookshelf' }, icon: '', current_version: '2.23.0', target_version: '2.36.0', check_status: 'available', operation: 'idle', update_ready: true, update_token: 'checked-2.36.0', rollback_available: true, rollback_version: '2.22.0', rollback_date: '2026-09-06T00:00:00Z', ...overrides })
const response = apps => ({ data: { data: apps, combined_updates_supported: true } })
const flush = async () => { for (let i = 0; i < 12; i++) await Promise.resolve() }
const wrappers = []
function render() {
  const wrapper = mount(AppUpdates, {
    mocks: { $t: (key, values = {}) => key.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? name) },
    stubs: { 'b-modal': { props: ['active'], template: '<div v-if="active"><slot /></div>' } },
  })
  wrappers.push(wrapper)
  return wrapper
}
beforeEach(() => {
  vi.useFakeTimers(); vi.clearAllMocks()
  updates.list.mockResolvedValue(response([app()]))
  updates.check.mockResolvedValue(response([app()]))
  updates.update.mockResolvedValue({}); updates.rollback.mockResolvedValue({})
})
afterEach(() => { wrappers.splice(0).forEach(w => w.destroy()); vi.useRealTimers() })

describe('Unified app updates', () => {
  it('shows an Update button for the newer registry version without a source selector', async () => {
    const wrapper = render(); await flush()
    expect(updates.check).toHaveBeenCalledWith()
    expect(wrapper.find('select').exists()).toBe(false)
    expect(wrapper.find('.app-row').text()).toContain('Audiobookshelf')
    expect(wrapper.find('.app-row').text()).toContain('2.23.0')
    expect(wrapper.find('.app-row').text()).toContain('2.36.0')
    expect(wrapper.find('.update-actions button').text()).toBe('Update')
    expect(wrapper.find('.update-actions button').attributes('disabled')).toBeUndefined()
    expect(wrapper.text()).toContain('1 update available')
    await wrapper.find('.update-actions button').trigger('click')
    expect(wrapper.find('.confirmation-version').text()).toContain('2.36.0')
    await wrapper.find('.confirm-button').trigger('click'); await flush()
    expect(updates.update).toHaveBeenCalledWith('audiobookshelf', 'checked-2.36.0')
  })
  it('keeps technical image references under closed details and hides image hashes', async () => {
    const item = app({ registry_images: [{ service: 'main', installed_image: 'ghcr.io/advplyr/audiobookshelf:2.23.0', latest_image: 'ghcr.io/advplyr/audiobookshelf:2.36.0', current_image_id: 'sha256:abc', latest_image_id: 'sha256:def' }] })
    updates.list.mockResolvedValue(response([item])); updates.check.mockResolvedValue(response([item]))
    const wrapper = render(); await flush()
    expect(wrapper.find('details').attributes('open')).toBeUndefined()
    expect(wrapper.find('.app-row').text()).not.toContain('ghcr.io')
    expect(wrapper.find('details').text()).toContain('ghcr.io/advplyr/audiobookshelf:2.36.0')
    expect(wrapper.text()).not.toContain('sha256:')
  })
  it('shows installed and registry versions behind the same latest tag', async () => {
    const image = 'linuxserver/radarr:latest'
    const item = app({ id: 'radarr', title: { en_us: 'Radarr' }, current_version: '5.0.3.8127-ls190', target_version: '5.1.0.9000-ls200', registry_images: [{ service: 'radarr', installed_image: image, latest_image: image, current_version: '5.0.3.8127-ls190', latest_version: '5.1.0.9000-ls200' }] })
    updates.list.mockResolvedValue(response([item])); updates.check.mockResolvedValue(response([item]))
    const wrapper = render(); await flush()
    expect(wrapper.find('.app-row').text()).toContain('5.0.3.8127-ls190')
    expect(wrapper.find('.app-row').text()).toContain('5.1.0.9000-ls200')
    const details = wrapper.find('details').text()
    expect(details).toContain('Installed5.0.3.8127-ls190')
    expect(details).toContain('Update5.1.0.9000-ls200')
    expect(details.split(image)).toHaveLength(2)
    expect(details).not.toContain('app store defaults')
  })
  it('distinguishes unpublished versions using immutable build IDs', async () => {
    const item = app({ registry_images: [{ service: 'main', installed_image: 'demo:latest', latest_image: 'demo:latest', current_image_id: 'sha256:abcdef0123456789', latest_image_id: 'sha256:987654fedcba1234' }] })
    updates.list.mockResolvedValue(response([item])); updates.check.mockResolvedValue(response([item]))
    const wrapper = render(); await flush()
    expect(wrapper.find('details').text()).toContain('Build abcdef012345')
    expect(wrapper.find('details').text()).toContain('Build 987654fedcba')
  })
  it('labels identical images as pinning without counting a software update', async () => {
    const item = app({ id: 'npm', title: { en_us: 'Nginx Proxy Manager' }, update_kind: 'pin', current_version: '2.15.1', target_version: '2.15.1', registry_images: [{ service: 'npm', current_version: '2.15.1', latest_version: '2.15.1', current_image_id: 'sha256:same', latest_image_id: 'sha256:same', installed_image: 'jc21/nginx-proxy-manager:latest', latest_image: 'jc21/nginx-proxy-manager:2.15.1' }] })
    updates.list.mockResolvedValue(response([item])); updates.check.mockResolvedValue(response([item]))
    const wrapper = render(); await flush()
    expect(wrapper.find('.update-actions button').text()).toBe('Pin version')
    expect(wrapper.find('.app-version').text()).toBe('2.15.1 · Already installed')
    expect(wrapper.find('.group-header h3').text()).toBe('Version pinning')
    expect(wrapper.find('.overview-count').text()).toBe('Installed versions can be pinned')
    expect(wrapper.text()).not.toContain('New update available')
    expect(wrapper.find('details').text()).toContain('Pinned image')
    await wrapper.find('.update-actions button').trigger('click')
    expect(wrapper.find('.modal-card-title').text()).toBe('Pin current version')
    expect(wrapper.find('.confirmation-version').text()).not.toContain('→')
    expect(wrapper.find('.modal-card-body').text()).toContain('software version stays the same')
    expect(wrapper.find('.confirm-button').text()).toBe('Pin version')
    await wrapper.find('.confirm-button').trigger('click'); await flush()
    expect(updates.update).toHaveBeenCalledWith('npm', item.update_token)
  })
  it('keeps sidecar and same-version rebuilds in real updates', async () => {
    const item = app({ update_kind: 'update', current_version: '2.15.1', target_version: '2.15.1' })
    const pinned = app({ id: 'pin', update_kind: 'pin', current_version: '1.0.0', target_version: '1.0.0' })
    updates.list.mockResolvedValue(response([item, pinned])); updates.check.mockResolvedValue(response([item, pinned]))
    const wrapper = render(); await flush()
    expect(wrapper.find('.overview-count').text()).toBe('1 update available')
    expect(wrapper.find('.app-version').text()).toContain('New update available')
    expect(wrapper.find('.update-actions button').text()).toBe('Update')
  })
  it('shows pending apps and errors while hiding current apps', async () => {
    const apps = [app(), app({ id: 'broken', title: { en_us: 'Broken' }, check_status: 'failed', update_ready: false, check_error: 'Registry unavailable' }), app({ id: 'current', title: { en_us: 'Current' }, check_status: 'up_to_date', update_ready: false })]
    updates.list.mockResolvedValue(response(apps)); updates.check.mockResolvedValue(response(apps))
    const wrapper = render(); await flush()
    expect(wrapper.findAll('.group-header h3').wrappers.map(w => w.text())).toEqual(['Available updates', 'Needs attention'])
    expect(wrapper.find('[data-app-id="broken"]').text()).toContain('Registry unavailable')
    expect(wrapper.find('[data-app-id="broken"] .update-button').exists()).toBe(false)
    expect(wrapper.find('[data-app-id="current"]').exists()).toBe(false)
  })
  it('uses a new-build label when the image changes under the same tag', async () => {
    const item = app({ current_version: 'latest', target_version: 'latest' })
    updates.list.mockResolvedValue(response([item])); updates.check.mockResolvedValue(response([item]))
    const wrapper = render(); await flush()
    expect(wrapper.find('.app-version').text()).toContain('New update available')
    expect(wrapper.find('.update-button').exists()).toBe(true)
  })
  it('explains older backend support without offering an unsupported registry update', async () => {
    updates.list.mockResolvedValue({ data: { data: [app({ update_ready: false })], registry_supported: true } })
    const wrapper = render(); await flush()
    expect(wrapper.text()).toContain('require a newer CasaOS app-management service')
    expect(updates.check).not.toHaveBeenCalled()
    expect(wrapper.find('.update-actions button').exists()).toBe(false)
  })
  it('shows endpoint failure and empty states separately', async () => {
    updates.list.mockRejectedValue({ response: { status: 404 } })
    let wrapper = render(); await flush()
    expect(wrapper.text()).toContain('require a newer CasaOS app-management service')
    wrapper.destroy()
    updates.list.mockResolvedValue(response([])); updates.check.mockResolvedValue(response([]))
    wrapper = render(); await flush()
    expect(wrapper.text()).toContain('No installed apps')
    expect(wrapper.text()).not.toContain('All apps are up to date')
  })
  it('prevents duplicate submissions and preserves the reviewed token during polling', async () => {
    const wrapper = render(); await flush()
    wrapper.vm.confirm(wrapper.vm.apps[0], false)
    updates.list.mockResolvedValue(response([app({ target_version: '2.37.0', update_token: 'new-token' })]))
    await wrapper.vm.refresh(false)
    let finish
    updates.update.mockImplementation(() => new Promise(resolve => { finish = resolve }))
    const first = wrapper.vm.submit(); await wrapper.vm.submit()
    expect(updates.update).toHaveBeenCalledOnce()
    expect(updates.update).toHaveBeenCalledWith('audiobookshelf', 'checked-2.36.0')
    finish({}); await first
  })
  it('keeps stale-plan and other action errors visible in the confirmation', async () => {
    const wrapper = render(); await flush()
    updates.update.mockRejectedValue({ response: { status: 409, data: { message: 'Check for updates again' } } })
    wrapper.vm.confirm(wrapper.vm.apps[0], false); await wrapper.vm.submit()
    expect(wrapper.vm.confirmOpen).toBe(true)
    expect(wrapper.find('[role="alert"]').text()).toContain('Check for updates again')
  })
  it('keeps restore in Details with a data-preservation confirmation', async () => {
    const wrapper = render(); await flush()
    await wrapper.find('.restore-row button').trigger('click')
    expect(wrapper.text()).toContain('cannot undo database changes')
    expect(wrapper.find('.confirmation-version').text()).toContain('2.22.0')
    await wrapper.find('.confirm-button').trigger('click'); await flush()
    expect(updates.rollback).toHaveBeenCalledWith('audiobookshelf')
  })
  it('disables conflicting actions while updating and stops polling on close', async () => {
    const item = app({ operation: 'applying' })
    updates.list.mockResolvedValue(response([item])); updates.check.mockResolvedValue(response([item]))
    const wrapper = render(); await flush()
    expect(wrapper.find('.update-actions button').attributes('disabled')).toBeDefined()
    expect(wrapper.find('progress').exists()).toBe(true)
    expect(wrapper.text()).toContain('Starting updated app')
    wrapper.destroy()
    const count = updates.list.mock.calls.length
    await vi.advanceTimersByTimeAsync(30000)
    expect(updates.list).toHaveBeenCalledTimes(count)
  })

  it.each(['update', 'pin'])('removes a completed %s and polls status without another registry scan', async kind => {
    const item = app({ update_kind: kind })
    updates.list.mockResolvedValue(response([item])); updates.check.mockResolvedValue(response([item]))
    const wrapper = render(); await flush()
    updates.list.mockResolvedValue(response([app({ update_kind: kind, operation: 'applying' })]))
    await wrapper.find('.update-actions button').trigger('click')
    await wrapper.find('.confirm-button').trigger('click'); await flush()
    expect(wrapper.find('[data-app-id="audiobookshelf"]').exists()).toBe(true)
    expect(wrapper.find('progress').exists()).toBe(true)
    expect(wrapper.find('.header-actions .check-button').attributes('disabled')).toBeDefined()
    updates.list.mockResolvedValue(response([app({ operation: 'updated', check_status: 'up_to_date', current_version: '2.36.0', update_ready: false, update_token: '' })]))
    await vi.advanceTimersByTimeAsync(3000)
    expect(wrapper.find('[data-app-id="audiobookshelf"]').exists()).toBe(false)
    expect(wrapper.find('.updates-empty').text()).toContain('No pending updates')
    expect(wrapper.find('.restore-history').attributes('open')).toBeUndefined()
    expect(wrapper.find('.restore-history').text()).toContain('Audiobookshelf')
    await vi.advanceTimersByTimeAsync(45000)
    expect(updates.check).toHaveBeenCalledTimes(1)
    await wrapper.find('.header-actions .check-button').trigger('click'); await flush()
    expect(updates.check).toHaveBeenCalledTimes(2)
  })

  it('does not hide failed operations when the cached check says up to date', async () => {
    const item = app({ operation: 'failed', check_status: 'up_to_date', update_ready: false, error: 'Startup failed' })
    updates.list.mockResolvedValue(response([item])); updates.check.mockResolvedValue(response([item]))
    const wrapper = render(); await flush()
    expect(wrapper.find('[data-app-id="audiobookshelf"]').text()).toContain('Startup failed')
    expect(wrapper.find('.group-header').text()).toContain('Needs attention')
    expect(wrapper.find('.updates-empty').exists()).toBe(false)
  })

  it('restores a completed app from the separate recovery section', async () => {
    const item = app({ operation: 'updated', check_status: 'up_to_date', update_ready: false })
    updates.list.mockResolvedValue(response([item])); updates.check.mockResolvedValue(response([item]))
    const wrapper = render(); await flush()
    expect(wrapper.findAll('.update-card')).toHaveLength(0)
    await wrapper.find('.restore-history button').trigger('click')
    expect(wrapper.find('.modal-card-title').text()).toBe('Revert to previous version')
    await wrapper.find('.confirm-button').trigger('click'); await flush()
    expect(updates.rollback).toHaveBeenCalledWith(item.id)
  })

  it('confirms all available software updates once and preserves every reviewed token', async () => {
    const first = app()
    const second = app({ id: 'plex', title: { en_us: 'Plex' }, update_token: 'plex-reviewed' })
    const pin = app({ id: 'pin', update_kind: 'pin' })
    const busy = app({ id: 'busy', operation: 'pulling' })
    const failed = app({ id: 'failed', check_status: 'failed', update_ready: false })
    const current = app({ id: 'current', check_status: 'up_to_date', update_ready: false })
    updates.list.mockResolvedValue(response([first, second, pin, busy, failed, current]))
    const wrapper = render(); await flush()
    expect(wrapper.find('.update-all-button').text()).toBe('Update all (2)')
    await wrapper.find('.update-all-button').trigger('click')
    expect(wrapper.find('.modal-card-title').text()).toBe('Update all apps')
    expect(wrapper.findAll('.bulk-app-list li')).toHaveLength(2)
    updates.list.mockResolvedValue(response([app({ update_token: 'changed-token' }), { ...second, update_token: 'changed-plex-token' }]))
    await wrapper.vm.refresh(false)
    let finish
    updates.update.mockImplementation(id => id === first.id ? new Promise(resolve => { finish = resolve }) : Promise.resolve({}))
    const submitted = wrapper.vm.submit()
    await wrapper.vm.submit(); await flush()
    expect(updates.update.mock.calls).toEqual([[first.id, first.update_token], [second.id, second.update_token]])
    expect(wrapper.find('.update-all-button').attributes('disabled')).toBeDefined()
    finish({}); await submitted
    expect(wrapper.vm.confirmOpen).toBe(false)
    expect(wrapper.text()).toContain('Started 2 app updates.')
    expect(updates.check).not.toHaveBeenCalled()
  })

  it('keeps bulk launch failures visible and continues starting other apps', async () => {
    const items = [app(), app({ id: 'plex', title: { en_us: 'Plex' }, update_token: 'plex-token' })]
    updates.list.mockResolvedValue(response(items)); updates.check.mockResolvedValue(response(items))
    const wrapper = render(); await flush()
    updates.update.mockImplementation(id => id === 'plex'
      ? Promise.reject({ response: { status: 409, data: { message: 'Plex settings changed; check again' } } })
      : Promise.resolve({}))
    await wrapper.find('.update-all-button').trigger('click')
    await wrapper.find('.confirm-button').trigger('click'); await flush()
    expect(updates.update).toHaveBeenCalledTimes(2)
    expect(wrapper.text()).toContain('Started 1 of 2 updates')
    expect(wrapper.find('[data-app-id="plex"]').text()).toContain('Plex settings changed; check again')
    updates.list.mockResolvedValue(response([app({ operation: 'updated', check_status: 'up_to_date', update_ready: false }), items[1]]))
    await wrapper.vm.refresh(false)
    expect(wrapper.find('[data-app-id="audiobookshelf"]').exists()).toBe(false)
    expect(wrapper.find('[data-app-id="plex"]').text()).toContain('Plex settings changed; check again')
    expect(updates.check).toHaveBeenCalledTimes(1)
    updates.list.mockResolvedValue(response([app({ id: 'plex', operation: 'updated', check_status: 'up_to_date', update_ready: false })]))
    await wrapper.vm.refresh(false)
    expect(wrapper.find('[data-app-id="plex"]').exists()).toBe(false)
    expect(wrapper.vm.submissionErrors.plex).toBeUndefined()
    updates.list.mockRejectedValue({ response: { status: 500, data: { message: 'Could not read app status' } } })
    await wrapper.vm.refresh(false)
    expect(wrapper.find('.notice-error').text()).toContain('Could not read app status')
  })

  it('disables Update all when there are only pins or completed apps', async () => {
    const items = [app({ update_kind: 'pin' }), app({ id: 'current', check_status: 'up_to_date', update_ready: false })]
    updates.list.mockResolvedValue(response(items)); updates.check.mockResolvedValue(response(items))
    const wrapper = render(); await flush()
    expect(wrapper.find('.update-all-button').attributes('disabled')).toBeDefined()
    wrapper.vm.confirmAll()
    expect(wrapper.vm.confirmOpen).toBe(false)
    expect(updates.update).not.toHaveBeenCalled()
  })
})
